export const LUCIDE_ICONS: string[] = [
  'lucideBookOpen', 'lucideBookMarked', 'lucideBook', 'lucideGraduationCap', 'lucideSchool',
  'lucideUniversity', 'lucideLibrary', 'lucidePenTool', 'lucidePencil', 'lucideClipboard',
  'lucideFileText', 'lucideFileBadge', 'lucideAward', 'lucideMedal', 'lucideTrophy',
  'lucideStar', 'lucideTarget', 'lucideLightbulb', 'lucideBrain', 'lucideFlask',
  'lucideMicroscope', 'lucideCalculator', 'lucideCode', 'lucideCode2', 'lucideTerminal',
  'lucideMonitor', 'lucideLaptop', 'lucideCpu', 'lucideDatabase', 'lucideServer',
  'lucideGlobe', 'lucideGlobe2', 'lucideMap', 'lucideCompass', 'lucideNavigation',
  'lucideBriefcase', 'lucideBuilding', 'lucideBuilding2', 'lucideFactory', 'lucideStore',
  'lucideUsers', 'lucideUser', 'lucideUserCog', 'lucideHeartHandshake', 'lucideHandshake',
  'lucideHeart', 'lucideActivity', 'lucideStethoscope', 'lucidePill', 'lucideSyringe',
  'lucideLeaf', 'lucideTree', 'lucideSprout', 'lucideSun', 'lucideWind',
  'lucideZap', 'lucideFlame', 'lucideDiamond', 'lucideGem', 'lucideCrown',
  'lucideMusic', 'lucideCamera', 'lucidePalette', 'lucideImage', 'lucideVideo',
  'lucideMic', 'lucideRadio', 'lucidePodcast', 'lucideNewspaper', 'lucideRss',
  'lucideBarChart2', 'lucideBarChart', 'lucidePieChart', 'lucideTrendingUp', 'lucideLineChart',
  'lucideDollarSign', 'lucideCreditCard', 'lucideWallet', 'lucideBanknote', 'lucideLandmark',
  'lucideScale', 'lucideShield', 'lucideShieldCheck', 'lucideLock', 'lucideKey',
  'lucideWrench', 'lucideHammer', 'lucideHardHat', 'lucideTruck', 'lucidePlane',
  'lucideRocket', 'lucideSatellite', 'lucideAtom', 'lucideDna', 'lucideInfinity',
  'lucidePuzzle', 'lucideGrid', 'lucideLayout', 'lucideShapes', 'lucideComponent',
];
